export const mapCountry = {
  "United States of America": ["アメリカ合衆国", "アメリカ"],
  Argentina: ["アルゼンチン"],
  "United Kingdom": ["イギリス"],
  Italy: ["イタリア"],
  India: ["インド"],
  Indonesia: ["インドネシア"],
  Australia: ["オーストラリア"],
  Canada: ["カナダ"],
  "South Korea": ["韓国"],
  "Saudi Arabia": ["サウジアラビア"],
  China: ["中国"],
  Germany: ["ドイツ"],
  Turkey: ["トルコ"],
  Japan: ["日本"],
  Brazil: ["ブラジル"],
  France: ["フランス"],
  "South Africa": ["南アフリカ"],
  Mexico: ["メキシコ"],
  Russia: ["ロシア"],
  Algeria: ["AU"],
  Egypt: ["AU"],
  Morocco: ["AU"],
  "Sierra Leone": ["AU"],
  Angola: ["AU"],
  "Equatorial Guinea": ["AU"],
  Malawi: ["AU"],
  Somalia: ["AU"],
  Somaliland: ["AU"],
  Benin: ["AU"],
  Eritrea: ["AU"],
  Botswana: ["AU"],
  Mauritania: ["AU"],
  // "Burkina Faso": ["AU"],
  Ethiopia: ["AU"],
  Mauritius: ["AU"],
  "South Sudan": ["AU"],
  Burundi: ["AU"],
  Gambia: ["AU"],
  Mozambique: ["AU"],
  // Sudan: ["AU"],
  "Cape Verde": ["AU"],
  Ghana: ["AU"],
  Namibia: ["AU"],
  "United Republic of Tanzania": ["AU"],
  Cameroon: ["AU"],
  Nigeria: ["AU"],
  Togo: ["AU"],
  Chad: ["AU"],
  "Guinea Bissau": ["AU"],
  "Republic of Congo": ["AU"],
  Tunisia: ["AU"],
  Comoros: ["AU"],
  Kenya: ["AU"],
  Rwanda: ["AU"],
  Uganda: ["AU"],
  "Central African Republic": ["AU"],
  "Western Sahara": ["AU"],
  Lesotho: ["AU"],
  "United Arab Emirates": ["AU"],
  Zambia: ["AU"],
  "Ivory Coast": ["AU"],
  Liberia: ["AU"],
  Zimbabwe: ["AU"],
  Libya: ["AU"],
  "Democratic Republic of the Congo": ["AU"],
  Madagascar: ["AU"],
  "Sao Tome and Principe": ["AU"],
  Djibouti: ["AU"],
  Senegal: ["AU"],
  Seychelles: ["AU"],
  Austria: ["EU"],
  Belgium: ["EU"],
  Bulgaria: ["EU"],
  Croatia: ["EU"],
  Cyprus: ["EU"],
  "Czech Republic": ["EU"],
  Denmark: ["EU"],
  Estonia: ["EU"],
  Finland: ["EU"],
  Greece: ["EU"],
  Hungary: ["EU"],
  Ireland: ["EU"],
  Latvia: ["EU"],
  Lithuania: ["EU"],
  Luxembourg: ["EU"],
  Malta: ["EU"],
  Netherlands: ["EU"],
  Poland: ["EU"],
  Portugal: ["EU"],
  Romania: ["EU"],
  Slovakia: ["EU"],
  Slovenia: ["EU"],
  Spain: ["EU"],
  Sweden: ["EU"],
};
